####
#### The ontology description file for GOlr and AmiGO.
####
id: ontology
schema_generating: true
description: Gene Ontology Term, Synonym, or Definition.
display_name: Ontology
document_category: ontology_class
weight: 40
boost_weights: annotation_class^3.0 annotation_class_label^5.5 description^1.0 synonym^1.0 alternate_id^1.0
result_weights: annotation_class^8.0 description^6.0 source^4.0 idspace^3.5 synonym^3.0 alternate_id^2.0
filter_weights: source^4.0 idspace^3.5 subset^3.0 is_obsolete^0.0
fields:
  - id: id
    description: Term identifier.
    display_name: Acc
    type: string
    property: [getIdentifier]
  - id: annotation_class
    description: Term identifier.
    display_name: Term
    type: string
    property: [getIdentifier]
  - id: annotation_class_label
    description: Identifier.
    display_name: Term
    type: string
    property: [getLabel]
    searchable: true
## Ever used with terms?
# - id: descriptive_name
#     description: Term description.
#     display_name: Description
#     type: string
#     property: [descriptive_name]
#    searchable: true
  - id: description
    description: "Term definition."
    display_name: Definition
    type: string
    property: [getDef]
    searchable: true
  - id: source
    description: "Term namespace."
    display_name: Ontology source
    type: string
    property: [getNamespace]
  - id: idspace
    description: "Term ID space."
    display_name: Ontology ID space
    type: string
    property: [getIdSpace]
  - id: is_obsolete
    description: Is the term obsolete?
    display_name: Obsoletion
    type: boolean
    property: [getIsObsoleteBinaryString]
  - id: comment
    description: Term comments.
    display_name: Comments
    type: string
    property: [getComments]
    cardinality: multi
    searchable: true
  - id: synonym
    description: Term synonyms.
    display_name: Synonyms
    type: string
    property: [getOBOSynonymStrings]
    cardinality: multi
    searchable: true
  - id: alternate_id
    description: Alternate term identifier.
    display_name: Alt ID
    type: string
    property: [getAnnotationPropertyValues, alt_id]
    cardinality: multi
  - id: replaced_by
    description: Term that replaces this term.
    display_name: Replaced By
    type: string
    property: [getAnnotationPropertyValues, replaced_by]
    cardinality: multi
  - id: consider
    description: Others terms you might want to look at.
    display_name: Consider
    type: string
    property: [getAnnotationPropertyValues, consider]
    cardinality: multi
  - id: subset
    description: "Special use collections of terms."
    display_name: Subset
    type: string
    property: [getSubsets]
    cardinality: multi
  - id: definition_xref
    description: Definition cross-reference.
    display_name: Def xref
    type: string
    property: [getDefXref]
    cardinality: multi
  - id: database_xref
    description: Database cross-reference.
    display_name: DB xref
    type: string
    property: [getXref]
    cardinality: multi
  - id: isa_partof_closure
    description: "Ancestral terms (is_a/part_of)."
    display_name: Is-a/part-of
    type: string
    cardinality: multi
    property:
      - "getRelationIDClosure"
      - "BFO:0000050"
  - id: isa_partof_closure_label
    description: "Ancestral terms (is_a/part_of)."
    display_name: Is-a/part-of
    type: string
    cardinality: multi
    property:
      - "getRelationLabelClosure"
      - "BFO:0000050"
    searchable: true
  - id: regulates_closure
    description: "Ancestral terms (regulates, occurs in, capable_of)."
    display_name: Ancestor
    type: string
    cardinality: multi
    property:
      - "getRelationIDClosure"
      - "BFO:0000050"
      - "BFO:0000066"
      - "RO:0002211"
      - "RO:0002212"
      - "RO:0002213"
      - "RO:0002215"
      - "RO:0002216"
  - id: regulates_closure_label
    description: "Ancestral terms (regulates, occurs in, capable_of)."
    display_name: Ancestor
    type: string
    cardinality: multi
    property:
      - "getRelationLabelClosure"
      - "BFO:0000050"
      - "BFO:0000066"
      - "RO:0002211"
      - "RO:0002212"
      - "RO:0002213"
      - "RO:0002215"
      - "RO:0002216"
    searchable: true
  - id: topology_graph_json
    description: "JSON blob form of the local stepwise topology graph. Uses various relations (including regulates, occurs in, capable_of)."
    display_name: Topology graph (JSON)
    type: string
    property:
      - "getSegmentShuntGraphJSON"
      - "BFO:0000050"
      - "BFO:0000066"
      - "RO:0002211"
      - "RO:0002212"
      - "RO:0002213"
      - "RO:0002215"
      - "RO:0002216"
    indexed: false
  - id: regulates_transitivity_graph_json
    description: "JSON blob form of the local relation transitivity graph. Uses various relations (including regulates, occurs in, capable_of)."
    display_name: Regulates transitivity graph (JSON)
    type: string
    property:
      - "getLineageShuntGraphJSON"
      - "BFO:0000050"
      - "BFO:0000066"
      - "RO:0002211"
      - "RO:0002212"
      - "RO:0002213"
      - "RO:0002215"
      - "RO:0002216"
    indexed: false
  - id: neighborhood_graph_json
    description: "JSON blob form of all immediate neighbors of the term."
    display_name: Term neighborhood graph (JSON)
    type: string
    property:
      - "getNeighborsJSON"
    indexed: false
  - id: neighborhood_limited_graph_json
    description: "JSON blob form of all immediate neighbors of the term; in the case that there are too many neighbors to transport, the number will be artificially reduced."
    display_name: Term neighborhood limited graph (JSON)
    type: string
    property:
      - "getNeighborsLimitedJSON"
    indexed: false
  ## TODO/BUG: These are currently populated by junk functions.
  ## https://github.com/geneontology/amigo/issues/56
  - id: only_in_taxon
    description: "Only in taxon."
    display_name: Only in taxon
    type: string
    property: [getDummyString]
    searchable: true
  - id: only_in_taxon_label
    description: "Only in taxon label."
    display_name: Only in taxon
    type: string
    property: [getDummyString]
    searchable: true
  - id: only_in_taxon_closure
    description: "Only in taxon closure."
    display_name: Only in taxon (IDs)
    type: string
    cardinality: multi
    property: [getDummyStrings]
  - id: only_in_taxon_closure_label
    description: "Only in taxon label closure."
    display_name: Only in taxon
    type: string
    cardinality: multi
    property: [getDummyStrings]
    searchable: true
  ## TODO/BUG: These are currently populated by junk functions.
  ## Next items are defined in https://github.com/geneontology/amigo/issues/249
  - id: annotation_extension_owl_json
    description: "A non-lossy representation of conjunctions and disjunctions in c16 (JSON)."
    display_name: Annotation extension
    type: string
    property: [getDummyString]
  - id: annotation_relation
    description: "This is equivalent to the relation field in GPAD."
    display_name: Annotation relation
    type: string
    property: [getDummyString]
  - id: annotation_relation_label
    description: "This is equivalent to the relation field in GPAD."
    display_name: Annotation relation
    type: string
    property: [getDummyString]
    searchable: true
  - id: equivalent_class_expressions_json
    description: "For any class document C, this will contain json(CE) for all axioms of form EquivalentClasses(C ... CE ....)."
    display_name: Eq class expressions
    type: string
    property: [getDummyString]
  - id: disjoint_class_list
    description: "Disjoint classes."
    display_name: Disjoint classes
    type: string
    cardinality: multi
    property: [getDummyStrings]
  - id: disjoint_class_list_label
    description: "Disjoint classes."
    display_name: Disjoint classes
    type: string
    cardinality: multi
    searchable: true
    property: [getDummyStrings]
